---
- name: Install nvm
  sudo: False
  shell: creates=~/.nvm {{ item }}
  with_items:
    - git clone https://github.com/creationix/nvm.git ~/.nvm && cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`
