---
- name: Install the debs
  sudo: True
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - build-essential
    - curl
    - git
    - m4
    - ruby
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - libncursesw5-dev
    - zlib1g-dev
    - python-dev
    - cmake

- name: Install linuxbrew
  sudo: False
  git: repo=https://github.com/Homebrew/linuxbrew.git
       dest=~/.linuxbrew

- name: Copy linuxbrew patch
  sudo: False
  copy: src={{ patch_file }} dest=~/.linuxbrew/{{ patch_file }}

- name: Patch linuxbrew and tap peco
  sudo: False
  command: creates={{ patch_applied }} chdir=~/.linuxbrew {{ item }}
  with_items:
    - git apply {{ patch_file }}
    - bin/brew tap peco/peco
    - touch {{ patch_applied }}

- name: Install brew packages
  sudo: False
  command: ~/.linuxbrew/bin/brew install -v {{ item }}
  with_items:
    - fasd
    - tree
    - htop
    - the_silver_searcher
    - peco
