---
- name: Install the debs
  sudo: True
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - ngrep
    - sysstat

- name: Sync dotfiles
  sudo: False
  synchronize: src=~/Code/dotfiles dest=~
  tags: dotfiles

- name: Sync .oh-my-zsh
  sudo: False
  synchronize: src=~/.oh-my-zsh dest=~
  tags: dotfiles

- name: Link dotfiles
  sudo: False
  file:
    src: ~/dotfiles/{{ item }}
    dest: ~/.{{ item }}
    state: link
  with_items:
    - zshrc
    - zprofile
    - inputrc
    - vimrc
  tags: dotfiles
