---
- name: Make .vim directory
  sudo: False
  file:
    path: ~/.vim
    state: directory

- name: Sync dirs
  sudo: False
  synchronize: src=~/.vim/{{ item }} dest=~/.vim
  with_items:
    - bundle
    - eclim
    - plugin

- name: Rebuild YouCompleteMe
  sudo: False
  shell: chdir=~/.vim/bundle/YouCompleteMe {{ item }}
  with_items:
    - eval `~/.linuxbrew/bin/brew --env` && ./install.sh
