---
- name: Install vim
  sudo: True
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - vim

- name: Remove ~/.vim directory
  sudo: False
  file:
    path: ~/.vim
    state: absent

- name: Make .vim directory
  sudo: False
  file:
    path: ~/.vim
    state: directory

- name: Create archive
  sudo: False
  local_action: command chdir=~/.vim tar cvf {{ vim_archive }} bundle eclim plugin

- name: Unpack archive
  sudo: False
  unarchive: src={{ vim_archive }} dest=/home/{{ ansible_ssh_user }}/.vim

- name: Rebuild YouCompleteMe
  sudo: False
  shell: chdir=~/.vim/bundle/YouCompleteMe {{ item }}
  with_items:
    - eval `~/.linuxbrew/bin/brew --env` && ./install.sh
